version: '3.8'

services:
  database:
    container_name: devGroup-test-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=toysrus
      - MYSQL_TCP_PORT=3306
    ports:
      - 3307:3306
    build: database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h" ,localhost]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    container_name: devGroup-test-backend
    ports:
      - 3015:3015
    environment:
      - NODE_ENV=compose
    build: ./backend
    depends_on:
      database:
        condition: service_healthy
  frontend:
    container_name: devGroup-test-frontend
    ports:
      - 5173:80
    build: ./frontend
  